sonar.projectKey=andrea-ivanov
sonar.organization=andrea-ivanov
sonar.projectName=Wardrobe App

# Rutas del código fuente de Flutter
sonar.sources=mobile/lib
sonar.tests=mobile/test

# Reporte de cobertura (LCOV) generado por Flutter
sonar.dart.lcov.reportPaths=mobile/coverage/lcov.info

# Exclusiones MUY IMPORTANTES para Isar y el código autogenerado
sonar.exclusions=**/*.g.dart, **/*.freezed.dart, mobile/build/**, mobile/.dart_tool/**, mobile/coverage/**

sonar.sourceEncoding=UTF-8